#!/bin/sh -l
# FILENAME:  rnn_exp_hogun.sub

#PBS -V
#PBS -l nodes=1:ppn=1
#PBS -l walltime=20:00:00
#PBS -N rnn_exp_hogun
#PBS -l naccesspolicy=shared

# Print the hostname of the compute node on which this job is running.
/bin/hostname

cd $RCAC_SCRATCH
cd GraphDeepLearningMini/GraphDeepLearning/dri/experiments
module load anaconda
unset DISPLAY

time python rnnExperimentsHogunPerTrial.py $nettype $mem $minidim $deg $fname $trial $fold
