#!/bin/sh -l
# FILENAME:  rnn_prr.sub

#PBS -V
#PBS -l nodes=1:ppn=1
#PBS -l walltime=300:00:00
#PBS -N rnn_prr
#PBS -l naccesspolicy=shared
#PBS -p 10

# Print the hostname of the compute node on which this job is running.
/bin/hostname

cd /home/moore269/GraphDeepLearning/pylearn2/experiments/tests
module load python
unset DISPLAY

echo $nettype
echo $mem
echo $prtype
echo $singlepr
echo $test

time python rnnExperiments.py $nettype $mem $prtype $singlepr $data $biasself $degree
