#!/bin/sh -l
# FILENAME:  rnn_exp4.sub

#PBS -V
#PBS -l nodes=1:ppn=10
#PBS -l walltime=20:00:00
#PBS -N rnn_exp4
#PBS -l naccesspolicy=shared

# Print the hostname of the compute node on which this job is running.
/bin/hostname

cd $RCAC_SCRATCH
cd GraphDeepLearning3/GraphDeepLearning/pylearn2/experiments/tests/
module load python
unset DISPLAY

time python rnnExperiments.py $nettype $mem $prtype $singlepr $test $bias $deg $limit $summ $weight $nodeg $aug $rinit $usepr $gpu
